

class ChalengingTask_locators:
    Website = "https://atid.store/"
    Store_page = "//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[2]/a[1]"
    Atid_green_tshirt = "//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[5]/div[1]/a[1]"
    Black_hoodie = "//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[6]/div[1]/a[1]"
    Bright_gold_purse_with_chain = "//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[8]/div[1]/a[1]"
    Anchor_Bracelet = "//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[1]/div[1]/a[1]"
    Blue_denim_jeans = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/ul[1]/li[11]/div[1]/a[1]"
    Add_to_cart_button = "//button[contains(text(),'Add to cart')]"
    View_cart_button = "//body/div[@id='page']/div[@id='content']/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/a[1]"
    Check_out_selector = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/a[1]"
    Check_out_first_name = "//input[@id='billing_first_name']"
    Check_out_last_name = "//input[@id='billing_last_name']"
    Check_out_company_name = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[3]/div[1]/div[1]/div[1]/div[1]/p[3]/span[1]/input[1]"
    Check_out_country = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[3]/div[1]/div[1]/div[1]/div[1]/p[4]/span[1]/span[1]/span[1]/span[1]/span[1]"
    Check_out_billing_address = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[3]/div[1]/div[1]/div[1]/div[1]/p[5]/span[1]/input[1]"
    Check_out_billing_address2 = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[3]/div[1]/div[1]/div[1]/div[1]/p[6]/span[1]/input[1]"
    Check_out_post_code = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[3]/div[1]/div[1]/div[1]/div[1]/p[7]/span[1]/input[1]"
    Check_out_town = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[3]/div[1]/div[1]/div[1]/div[1]/p[8]/span[1]/input[1]"
    Check_out_phone = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[3]/div[1]/div[1]/div[1]/div[1]/p[10]/span[1]/input[1]"
    Check_out_email_address = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[3]/div[1]/div[1]/div[1]/div[1]/p[11]/span[1]/input[1]"
    Check_out_order_notes = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[3]/div[1]/div[1]/div[1]/div[1]/p[6]/span[1]/input[1]"
    Check_out_first_name_text = "yonas"
    Check_out_last_name_text = "amare"
    Check_out_company_name_text = "yonas plc"
    Check_out_country_text = "Israel"
    Check_out_billing_address_text = "58 רחוב הצדיק מירושלים"
    Check_out_billing_address_text2 = "Building 2"
    Check_out_post_code_text = "8461176"
    Check_out_town_text = "beersheba"
    Check_out_phone_text = "0555555555"
    Check_out_email_address_text = "yome3748@gmail.com"
    Check_out_order_notes_text = ""
    Place_order = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[3]/div[2]/div[1]/div[1]/button[1]"
    NAV_UL_PRICE = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/ul[1]"
    NAV_LI_PRICE = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/ul[1]/li[7]"
    Price = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/ul[1]/li[7]/div[2]/span[2]/ins[1]/span[1]/bdi[1]"
    nav_ul_our_bestseller = "//body/div[@id='page']/div[@id='content']/div[1]/div[1]/div[1]/div[4]/ul[1]"
    nav_li_our_best_seller = "//strong[contains(text(),'5.00')]"
    Contact_us_page = "//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[7]/a[1]"
    Name_input = "//input[@id='wpforms-15-field_0']"
    Subject_input = "//input[@id='wpforms-15-field_5']"
    Email_input = "//input[@id='wpforms-15-field_4']"
    Message_input = "//textarea[@id='wpforms-15-field_2']"
    Css_selector_name = "#wpforms-15-field_0"
    Css_selector_subject = "#wpforms-15-field_5"
    Css_selector_email = "#wpforms-15-field_4"
    Css_selector_message = "#wpforms-15-field_2"
    Input_text_for_name = "yonas amare"
    Input_text_for_subject = "QA automation atid.store website test"
    Input_text_for_email = "yonasamare2121@gamil.com"
    Input_text_for_message = "Hi, i am yonas i'm learning QA automation course and i make a test for the atid.store website"
    Send_messgae_button = "//button[@id='wpforms-submit-15']"






